#configuration file is created as we can change the configuration or code from here only and it will reflect the changes
#in the whole code. We didn't need to change the code from its place
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip #from where to download data
  local_data_file: artifacts/data_ingestion/data.zip  #how data will be downloaded
  unzip_dir: artifacts/data_ingestion
 
 #In data validation we check whether the 3 files that we have downloaded are available or not
data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]



data_transformation:
  root_dir: artifacts/data_transformation #after applying transformation it will save the transformed data
  data_path: artifacts/data_ingestion/samsum_dataset  #From here it will take the data it need for transformation
  tokenizer_name: google/pegasus-cnn_dailymail #pegasus-cnn-dailymail is the pretrained model used for summarization task, it
  #will download the tokenizer from here




model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail




model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv